<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        // module/action populate the columns added by
        // 2026_09_16_162633_add_module_and_action_to_permissions_table.php,
        // which PermissionController@grouped() and @modules() already group
        // by - without this, every permission's module/action stayed null
        // and the grouped-by-module permission UI would have nothing to
        // group on.
        $permissions = [
            'view dashboard' => ['dashboard', 'view'],
            'view employees' => ['employees', 'view'],
            'create employees' => ['employees', 'create'],
            'edit employees' => ['employees', 'edit'],
            'delete employees' => ['employees', 'delete'],
            'view employee details' => ['employees', 'view details'],
            'view departments' => ['departments', 'view'],
            'create departments' => ['departments', 'create'],
            'edit departments' => ['departments', 'edit'],
            'delete departments' => ['departments', 'delete'],
            'view designations' => ['designations', 'view'],
            'create designations' => ['designations', 'create'],
            'edit designations' => ['designations', 'edit'],
            'delete designations' => ['designations', 'delete'],
            'view attendance' => ['attendance', 'view'],
            'create attendance' => ['attendance', 'create'],
            'edit attendance' => ['attendance', 'edit'],
            'delete attendance' => ['attendance', 'delete'],
            'view leaves' => ['leaves', 'view'],
            'create leaves' => ['leaves', 'create'],
            'edit leaves' => ['leaves', 'edit'],
            'delete leaves' => ['leaves', 'delete'],
            'approve leaves' => ['leaves', 'approve'],
            'reject leaves' => ['leaves', 'reject'],
            'view payroll' => ['payroll', 'view'],
            'create payroll' => ['payroll', 'create'],
            'edit payroll' => ['payroll', 'edit'],
            'delete payroll' => ['payroll', 'delete'],
            'process payroll' => ['payroll', 'process'],
            'view reports' => ['reports', 'view'],
            'export reports' => ['reports', 'export'],
            'view users' => ['users', 'view'],
            'create users' => ['users', 'create'],
            'edit users' => ['users', 'edit'],
            'delete users' => ['users', 'delete'],
            'manage roles' => ['roles', 'manage'],
            'assign roles' => ['roles', 'assign'],
            'manage permissions' => ['permissions', 'manage'],
            'assign permissions' => ['permissions', 'assign'],
            'view employee drafts' => ['employee drafts', 'view'],
            'create employee drafts' => ['employee drafts', 'create'],
            'edit employee drafts' => ['employee drafts', 'edit'],
            'delete employee drafts' => ['employee drafts', 'delete'],
            'complete employee onboarding' => ['employee drafts', 'complete'],
            'create leave policies' => ['leave policies', 'create'],
            'edit leave policies' => ['leave policies', 'edit'],
            'delete leave policies' => ['leave policies', 'delete'],
            'view leave entitlements' => ['leave entitlements', 'view'],
            'create leave entitlements' => ['leave entitlements', 'create'],
            'edit leave entitlements' => ['leave entitlements', 'edit'],
            'delete leave entitlements' => ['leave entitlements', 'delete'],
            'view holidays' => ['holidays', 'view'],
            'create holidays' => ['holidays', 'create'],
            'edit holidays' => ['holidays', 'edit'],
            'delete holidays' => ['holidays', 'delete'],
            'create attendance policies' => ['attendance policies', 'create'],
            'edit attendance policies' => ['attendance policies', 'edit'],
            'delete attendance policies' => ['attendance policies', 'delete'],
            'create work schedules' => ['work schedules', 'create'],
            'edit work schedules' => ['work schedules', 'edit'],
            'delete work schedules' => ['work schedules', 'delete'],
            'create shifts' => ['shifts', 'create'],
            'edit shifts' => ['shifts', 'edit'],
            'delete shifts' => ['shifts', 'delete'],
            'create weekly offs' => ['weekly offs', 'create'],
            'edit weekly offs' => ['weekly offs', 'edit'],
            'delete weekly offs' => ['weekly offs', 'delete'],
            'create late policies' => ['late policies', 'create'],
            'edit late policies' => ['late policies', 'edit'],
            'delete late policies' => ['late policies', 'delete'],
            'create overtime policies' => ['overtime policies', 'create'],
            'edit overtime policies' => ['overtime policies', 'edit'],
            'delete overtime policies' => ['overtime policies', 'delete'],
            'create onboarding checklists' => ['onboarding checklists', 'create'],
            'edit onboarding checklists' => ['onboarding checklists', 'edit'],
            'delete onboarding checklists' => ['onboarding checklists', 'delete'],
        ];

        foreach ($permissions as $name => [$module, $action]) {
            Permission::updateOrCreate(['name' => $name], ['module' => $module, 'action' => $action]);
        }

        $roles = [
            'Super Admin' => Permission::all()->pluck('name')->all(),
            'Admin' => [
                'view dashboard',
                'view employees',
                'create employees',
                'edit employees',
                'delete employees',
                'view employee details',
                'view departments',
                'create departments',
                'edit departments',
                'delete departments',
                'view designations',
                'create designations',
                'edit designations',
                'delete designations',
                'view attendance',
                'create attendance',
                'edit attendance',
                'view leaves',
                'create leaves',
                'edit leaves',
                'approve leaves',
                'view payroll',
                'create payroll',
                'edit payroll',
                'view reports',
                'export reports',
                'view users',
                'create users',
                'edit users',
                'manage roles',
                'manage permissions',
                'assign roles',
                'assign permissions',
                'view employee drafts',
                'create employee drafts',
                'edit employee drafts',
                'delete employee drafts',
                'complete employee onboarding',
                'create leave policies',
                'edit leave policies',
                'delete leave policies',
                'create attendance policies',
                'edit attendance policies',
                'delete attendance policies',
                'create work schedules',
                'edit work schedules',
                'delete work schedules',
                'create shifts',
                'edit shifts',
                'delete shifts',
                'create weekly offs',
                'edit weekly offs',
                'delete weekly offs',
                'create late policies',
                'edit late policies',
                'delete late policies',
                'create overtime policies',
                'edit overtime policies',
                'delete overtime policies',
                'create onboarding checklists',
                'edit onboarding checklists',
                'delete onboarding checklists',
            ],
            'HR' => [
                'view dashboard',
                'view employees',
                'create employees',
                'edit employees',
                'view employee details',
                'view departments',
                'view designations',
                'view attendance',
                'create attendance',
                'edit attendance',
                'view leaves',
                'approve leaves',
                'reject leaves',
                'view reports',
                'export reports',
                'view employee drafts',
                'create employee drafts',
                'edit employee drafts',
                'delete employee drafts',
                'complete employee onboarding',
                'create leave policies',
                'edit leave policies',
                'create attendance policies',
                'edit attendance policies',
                'create work schedules',
                'edit work schedules',
                'create shifts',
                'edit shifts',
                'create weekly offs',
                'edit weekly offs',
                'create late policies',
                'edit late policies',
                'create overtime policies',
                'edit overtime policies',
                'create onboarding checklists',
                'edit onboarding checklists',
            ],
            'Manager' => [
                'view dashboard',
                'view employees',
                'view employee details',
                'view attendance',
                'create attendance',
                'view leaves',
                'approve leaves',
                'reject leaves',
                'view reports',
            ],
            'Team Leader' => [
                'view dashboard',
                'view employees',
                'view employee details',
                'view attendance',
                'create attendance',
                'edit attendance',
                'view leaves',
                'approve leaves',
                'reject leaves',
                'view reports',
            ],
            'Employee' => [
                'view dashboard',
                'view employee details',
                'view attendance',
                'create attendance',
                'view leaves',
                'create leaves',
                'edit leaves',
            ],
        ];

        foreach ($roles as $roleName => $allowedPermissions) {
            $role = Role::firstOrCreate(['name' => $roleName]);
            $role->syncPermissions($allowedPermissions);
        }

        $superAdmin = User::firstOrCreate([
            'email' => env('ADMIN_EMAIL'),
        ], [
            'name' => 'Super Admin',
            'password' => Hash::make(env('ADMIN_PASSWORD')),
        ]);

        $superAdmin->assignRole('Super Admin');
    }
}
